export const GET_DAILY_STATE = "GET_DAILY_STATE"
export const GET_HOURLY_STATE = "GET_HOURLY_STATE"
export const SET_ALERT = "SET_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"
export const GET_ERROR = "GET_ERROR"
export const GET_DAILY_EVENT = "GET_DAILY_EVENT"
export const GET_HOURLY_EVENT = "GET_HOURLY_EVENT"





